# Generated by Django 5.1.1 on 2024-10-19 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0005_samplemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SampleModel',
        ),
    ]
