# Generated by Django 5.1.1 on 2024-10-19 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0006_delete_samplemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
